[supervisord]
nodaemon=true

; Executa os comandos Artisan antes de subir os serviços
[program:artisan-setup]
command=/bin/bash -c "php /var/www/html/artisan config:clear && php artisan route:clear && php artisan view:clear && php artisan cache:clear && php artisan config:cache && php artisan route:cache && php artisan storage:link || true"
priority=1
autostart=true
startretries=0
stderr_logfile=/var/log/supervisor/artisan-setup.err.log
stdout_logfile=/var/log/supervisor/artisan-setup.out.log

[program:php-fpm]
command=php-fpm
priority=10
autostart=true
startretries=3
stderr_logfile=/var/log/supervisor/php-fpm.err.log
stdout_logfile=/var/log/supervisor/php-fpm.out.log

[program:nginx]
command=nginx -g "daemon off;"
priority=20
autostart=true
startretries=3
stderr_logfile=/var/log/supervisor/nginx.err.log
stdout_logfile=/var/log/supervisor/nginx.out.log
