[supervisord]
nodaemon=true

[program:php-fpm]
command=docker-php-entrypoint php-fpm
autostart=true
autorestart=true
priority=1

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
priority=2
